<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Default.aspx.cs" Inherits="AspnTreeViewFiles.Default" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
        <div>
            <asp:TreeView ID="Tv1" runat="server" OnTreeNodePopulate="Tv1_TreeNodePopulate" AutoGenerateDataBindings="false" ExpandDepth="0">
                <Nodes>
                    <asp:TreeNode Value="C:" Text="Arquivos" SelectAction="Select" PopulateOnDemand="true"></asp:TreeNode>
                </Nodes>
            </asp:TreeView>
        </div>
        <asp:TreeView ID="Tv1" runat="server" OnTreeNodePopulate="Tv1_TreeNodePopulate">
        </asp:TreeView>
    </form>
</body>
</html>
